### ISSUE TITLE
Issue in viewing my ECG signal correctly

### ISSUE THREAD

**Issue by Mehafatima1** [perakakis/HEPLAB#1]
Hello.

I am having trouble withe viewing my ECG signals. I am attaching figures for reference:

Slide 1: Shows how my ECG channel appears on data scroll.  (I have viewed it on a scale of 100 so this is why it doesn't appear as a proper signal, it shows clear ECG signal at 1000 scale)

Slide 2: Shows how my ECG signal appear on HEPLAB GUI. 

Slide 3: Shows that after detecting peaks using ecgfast, my IBIs appear really weird. 

I am pre-processing data by filtering through FIR filter at 1 and 40 Hz. Then I open it in HEPLAB and again filter it at 3 and 30 Hz as indicated in the guide. My ECG signals otherwise appear perfect but I am having challenges with viewing them on HEPLAB. I am entering sampling rate as 250 Hz while opening my .txt file. Can someone please help where am I missing something? [
![Slide1](https://user-images.githubusercontent.com/69713819/90310000-cb30eb00-df06-11ea-866f-bb9ceee18d04.JPG)
![Slide2](https://user-images.githubusercontent.com/69713819/90310001-cc621800-df06-11ea-8e1a-d1af308eb718.JPG)
![Slide3](https://user-images.githubusercontent.com/69713819/90310004-ccfaae80-df06-11ea-82d7-ea0ceda70dac.JPG)

](url)

**Comment by perakakis** [comment]
Could you please send me by email (perakakis AT gmail DOT com) the dataset so I can have a look and help resolve this problem?

**Comment by perakakis** [comment]
I applied a 10Hz lowpass filter and the Pan-Tompkin algorithm and everything looks correct. I have not been able to reproduce your figures from the data you sent me.

![Screen Shot 2020-09-02 at 14 41 31](https://user-images.githubusercontent.com/7551266/91982471-93a9a780-ed2a-11ea-8ce0-8384f3dd47fb.png)

![Screen Shot 2020-09-02 at 14 41 46](https://user-images.githubusercontent.com/7551266/91982596-c489dc80-ed2a-11ea-9434-db47220050ec.png)

**Comment by Mehafatima1** [comment]
Thank you so much Perakakis
